services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  mysql_data: